language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-renderer-sass --save
  - npm install hexo-deployer-git --save 

#before_script:
 # - npm install -g gulp

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "SMartBot"
  - git config user.email "375584908@qq.com"
  - git add .
  - git commit -m "Update Source Codes."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: https://github.com/SMartQi/Live-the-Life.git
