language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-renderer-sass --save
  - npm install hexo-deployer-git --save 

#before_script:
 # - npm install -g gulp

script:
  - hexo generate
  - hexo deploy

branches:
  only:
    - master
env:
 global:
   - GH_REF: https://github.com/SMartQi/Live-the-Life.git
